/* INVENTARIO DE CARTERA — ACTUACIONES / EXPEDIENTES — ULTRA 20261010.9 */
(function(){
  const TYPE='actuaciones';
  const DATES=new Set(['fecha_prescripcion','fecha_aviso_cobro','fecha_opp','fecha_embargo','fecha_desembargo','fecha_investigacion_bienes','fecha_mandamiento_pago']);
  const F=[['nit','NIT','text'],['razon_social','RAZÓN SOCIAL','text'],['expediente','EXPEDIENTE','text'],['cuantia','CUANTÍA','currency'],['ano','AÑO','text'],['periodo','PERÍODO','text'],['obligacion','OBLIGACIÓN','select'],['tipo_obl','TIPO OBL','select'],['fecha_prescripcion','FECHA PRESCRIPCIÓN','date'],['aplicativo','APLICATIVO','select'],['estado','ESTADO','select'],['estado_sipac','ESTADO SIPAC','select'],['tramite_en_curso','TRÁMITE EN CURSO','derived'],['fecha_aviso_cobro','FECHA AVISO COBRO','date'],['fecha_opp','FECHA OPP','date'],['fecha_embargo','FECHA EMBARGO','date'],['fecha_desembargo','FECHA DESEMBARGO','date'],['fecha_investigacion_bienes','FECHA INVESTIGACIÓN BIENES','date'],['fecha_mandamiento_pago','FECHA MANDAMIENTO PAGO','date'],['observaciones','OBSERVACIONES','textarea']];
  let dataSig='',rowsCacheKey='',rowsCache=null,installed=false;
  const norm=v=>String(v??'').trim().toLowerCase();
  const tramite=r=>r?.fecha_desembargo?'DESEMBARGADO':r?.fecha_mandamiento_pago?'MANDAMIENTO DE PAGO':r?.fecha_investigacion_bienes?'INVESTIGACIÓN DE BIENES':r?.fecha_embargo?'EMBARGADO':r?.fecha_opp?'OPP':r?.fecha_aviso_cobro?'AVISO DE COBRO':null;
  const signature=rows=>rows?.length?(rows.length+':'+String(rows[0]?.id||'')+':'+String(rows[rows.length-1]?.id||'')): '0';
  function rebuild(){const rows=Array.isArray(cache.actuaciones)?cache.actuaciones:[];for(const r of rows){r.tramite_en_curso=tramite(r);r.__ax_search=[r.nit,r.razon_social,r.expediente].map(norm).filter(Boolean).join(' | ');}dataSig=signature(rows);rowsCacheKey='';rowsCache=null;}
  function ensure(){const rows=Array.isArray(cache.actuaciones)?cache.actuaciones:[];if(signature(rows)!==dataSig)rebuild();}
  function getRows(){ensure();const q=String(document.getElementById('search')?.value||'').trim(),st=tableState[TYPE]||{filters:{}};const key=q+'|'+JSON.stringify(st.filters||{})+'|'+String(st.sortKey||'')+'|'+String(st.asc!==false)+'|'+dataSig;if(key===rowsCacheKey&&rowsCache)return rowsCache;let out=cache.actuaciones||[];const nq=norm(q);if(nq)out=out.filter(r=>String(r.__ax_search||'').includes(nq));out=filterRows(TYPE,out);out=sortRows(TYPE,out);rowsCache=out;rowsCacheKey=key;return out;}
  const display=(r,k,t)=>{const v=r?.[k];if(v===null||v===undefined||v==='')return '';if(t==='currency')return money(v);if(t==='date')return displayDate(v);return String(v);};
  const row=r=>'<tr data-ax-row="'+Number(r.id)+'">'+F.map(([k,,t])=>{const v=display(r,k,t),c=t==='currency'?' money':t==='textarea'?' observation':'';return '<td data-ax-cell="'+esc(k)+'" title="'+esc(v)+'"><span class="ax-display'+c+'">'+esc(v)+'</span></td>';}).join('')+'</tr>';
  const values=(k,current)=>{const s=new Set((cache.actuaciones||[]).map(r=>String(r?.[k]??'').trim().toUpperCase()).filter(Boolean));if(current)s.add(String(current).trim().toUpperCase());return [...s].sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));};
  async function editCell(td){
    if(td.dataset.axEditing==='1'||td.dataset.axCell==='tramite_en_curso')return;const tr=td.closest('tr[data-ax-row]');if(!tr)return;const id=Number(tr.dataset.axRow),key=td.dataset.axCell,def=F.find(x=>x[0]===key);if(!def)return;const rec=(cache.actuaciones||[]).find(x=>Number(x.id)===id);if(!rec)return;const type=def[2],old=rec[key]??'';td.dataset.axEditing='1';let editor;
    if(type==='select'){editor=document.createElement('select');editor.className='ax-cell-edit ax-cell-select';editor.innerHTML='<option value="">SELECCIONAR...</option>'+values(key,old).map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');editor.value=String(old||'').toUpperCase();}
    else{editor=type==='textarea'?document.createElement('textarea'):document.createElement('input');editor.className='ax-cell-edit'+(type==='currency'?' ax-cell-money':'')+(type==='date'?' ax-cell-date':'')+(type==='textarea'?' ax-cell-observation':'');editor.type='text';editor.inputMode=type==='currency'||type==='date'?'numeric':'text';editor.value=type==='currency'?moneyInput(old):type==='date'?displayDate(old):String(old||'');if(type==='date'){editor.maxLength=10;editor.placeholder='DD/MM/AA';editor.addEventListener('input',()=>{if(typeof formatDateTyping==='function')editor.value=formatDateTyping(editor.value);});}editor.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();cancel();}if(e.key==='Enter'&&type!=='textarea'){e.preventDefault();editor.blur();}if(e.ctrlKey&&String(e.key).toLowerCase()==='enter'&&type==='textarea'){e.preventDefault();editor.blur();}});}
    let done=false;const cancel=()=>{if(done)return;done=true;td.dataset.axEditing='';td.innerHTML='<span class="ax-display">'+esc(display(rec,key,type))+'</span>';};
    const commit=async()=>{if(done)return;done=true;const fn=type==='date'?(window.updateInlineDate||window.updateInlineField):window.updateInlineField;if(typeof fn!=='function'){cancel();return;}const ok=await fn(TYPE,id,key,editor.value,editor);if(!ok){done=false;editor.focus();return;}rec[key]=type==='date'?(typeof isoFromDateInput==='function'?isoFromDateInput(editor.value):editor.value):type==='currency'?(typeof parseMoney==='function'?parseMoney(editor.value):editor.value):String(editor.value||'').trim().toUpperCase();td.dataset.axEditing='';td.innerHTML='<span class="ax-display">'+esc(display(rec,key,type))+'</span>';if(DATES.has(key)){rec.tramite_en_curso=tramite(rec);const t=tr.querySelector('td[data-ax-cell="tramite_en_curso"]');if(t)t.innerHTML='<span class="ax-display">'+esc(rec.tramite_en_curso||'')+'</span>';}rowsCacheKey='';};
    td.innerHTML='';td.appendChild(editor);editor.addEventListener('blur',commit,{once:true});if(type==='select')editor.addEventListener('change',commit,{once:true});editor.focus();if(editor.select)editor.select();
  }
  function bind(){if(installed)return;installed=true;document.addEventListener('click',e=>{const td=e.target.closest?.('#content td[data-ax-cell]');if(!td||e.target.closest('nav'))return;const title=String(document.getElementById('title')?.textContent||'').trim().toUpperCase();if(title!=='ACTUACIONES / EXPEDIENTES')return;if(e.target.closest('input,select,textarea,.column-filter-panel,.filter-icon,button'))return;editCell(td);},false);}
  function listFast(type){if(type!==TYPE)return false;const rows=getRows(),q=String(document.getElementById('search')?.value||'').trim();const html='<div class="toolbar"><button onclick="openModal(\'actuaciones\')">+ NUEVO</button><button class="alt" onclick="importXlsx(\'actuaciones\')">IMPORTAR XLSX</button><button class="alt" onclick="exportXlsx(\'actuaciones\')">EXPORTAR XLSX</button><button class="alt clear-filters-btn" onclick="clearAllFilters()">LIMPIAR FILTROS</button>'+(q?'<span class="sort-note">BUSCANDO: '+esc(q.toUpperCase())+'</span>':'')+'</div><div class="tablewrap"><table class="resizable-table actuaciones-expedientes-table ax-fast"><thead><tr>'+F.map(([k,l])=>sortHeader(TYPE,k,l)).join('')+'</tr></thead><tbody>'+(rows.length?rows.map(row).join(''):'<tr><td colspan="20" class="empty">NO HAY REGISTROS PARA EL FILTRO ACTUAL</td></tr>')+'</tbody></table></div>';$('content').innerHTML=html;const table=$('content').querySelector('table');if(table&&typeof applySavedColumnWidths==='function')applySavedColumnWidths(table,TYPE);if(table&&!loadColumnWidths().actuaciones?.observaciones){const th=table.querySelector('th[data-column-key="observaciones"]');if(th){th.style.width='1000px';th.style.minWidth='1000px';}}return true;}
  function install(){if(window.__ACTUACIONES_ULTRA_20261010_9__)return;window.__ACTUACIONES_ULTRA_20261010_9__=true;window.__ACTUACIONES_ULTRA_VERSION__='20261010.9';bind();const nativeList=window.list;window.list=function(type){if(type===TYPE)return listFast(type);return nativeList.apply(this,arguments);};const s=document.createElement('style');s.id='actuaciones-ultra-20261010-9';s.textContent='#content .actuaciones-expedientes-table.ax-fast{table-layout:auto}#content .actuaciones-expedientes-table tbody tr{content-visibility:auto;contain-intrinsic-size:30px}#content .actuaciones-expedientes-table td{contain:paint style}#content .ax-display{display:block;min-height:22px;padding:5px 6px;box-sizing:border-box;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:text}#content .ax-display.observation{white-space:normal}#content .ax-cell-edit{width:100%;box-sizing:border-box;border:1px solid #8aa9bf;background:#fff;border-radius:5px;padding:5px 6px;font:inherit;font-size:11px;color:inherit;text-transform:uppercase;outline:none}#content .ax-cell-money{text-align:right;text-transform:none}#content .ax-cell-observation{min-width:240px;white-space:normal}';document.head.appendChild(s);ensure();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,80));else setTimeout(install,80);
})();
