/* ACTUACIONES / EXPEDIENTES — RENDIMIENTO ULTRA + TRÁMITE AUTOMÁTICO + EDICIÓN */
(function(){
  const TYPE='actuaciones', DATES=new Set(['fecha_prescripcion','fecha_aviso_cobro','fecha_opp','fecha_embargo','fecha_desembargo','fecha_investigacion_bienes','fecha_mandamiento_pago']), SELECTS=new Set(['obligacion','tipo_obl','aplicativo','estado','estado_sipac']);
  const F=[['nit','NIT','text'],['razon_social','RAZÓN SOCIAL','text'],['expediente','EXPEDIENTE','text'],['cuantia','CUANTÍA','currency'],['ano','AÑO','text'],['periodo','PERÍODO','text'],['obligacion','OBLIGACIÓN','select'],['tipo_obl','TIPO OBL','select'],['fecha_prescripcion','FECHA PRESCRIPCIÓN','date'],['aplicativo','APLICATIVO','select'],['estado','ESTADO','select'],['estado_sipac','ESTADO SIPAC','select'],['tramite_en_curso','TRÁMITE EN CURSO','derived'],['fecha_aviso_cobro','FECHA AVISO COBRO','date'],['fecha_opp','FECHA OPP','date'],['fecha_embargo','FECHA EMBARGO','date'],['fecha_desembargo','FECHA DESEMBARGO','date'],['fecha_investigacion_bienes','FECHA INVESTIGACIÓN BIENES','date'],['fecha_mandamiento_pago','FECHA MANDAMIENTO PAGO','date'],['observaciones','OBSERVACIONES','textarea']];
  let cacheRevision=0,rowsCacheKey='',rowsCache=null,dataSignature='';
  function isAct(){return String(window.view||'').toLowerCase()===TYPE||String(document.getElementById('title')?.textContent||'').trim().toUpperCase()==='ACTUACIONES / EXPEDIENTES';}
  function norm(v){return String(v??'').trim().toLowerCase();}
  function tramite(r){if(r?.fecha_desembargo)return 'DESEMBARGADO';if(r?.fecha_mandamiento_pago)return 'MANDAMIENTO DE PAGO';if(r?.fecha_investigacion_bienes)return 'INVESTIGACIÓN DE BIENES';if(r?.fecha_embargo)return 'EMBARGADO';if(r?.fecha_opp)return 'OPP';if(r?.fecha_aviso_cobro)return 'AVISO DE COBRO';return null;}
  function refreshTramite(r){if(!r)return;const n=tramite(r);r.tramite_en_curso=n;const tr=document.querySelector('tr[data-ax-row="'+Number(r.id)+'"]'),td=tr?.querySelector('td[data-ax-cell="tramite_en_curso"]');if(td){td.textContent=n||'';td.title=n||'';}}
  window.__AX_REFRESH_TRAMITE=refreshTramite;
  function rebuild(){const rows=Array.isArray(cache.actuaciones)?cache.actuaciones:[];for(const r of rows){r.__ax_search=['nit','razon_social','expediente'].map(k=>norm(r?.[k])).filter(Boolean).join(' | ');refreshTramite(r);}dataSignature=rows.length+':'+String(rows[0]?.id||'')+':'+String(rows[rows.length-1]?.id||'');rowsCacheKey='';rowsCache=null;cacheRevision++;}
  function ensure(){const rows=Array.isArray(cache.actuaciones)?cache.actuaciones:[],sig=rows.length+':'+String(rows[0]?.id||'')+':'+String(rows[rows.length-1]?.id||'');if(sig!==dataSignature)rebuild();}
  function getRows(){ensure();const q=String(document.getElementById('search')?.value||'').trim(),filters=tableState[TYPE]?.filters||{},st=tableState[TYPE]||{},key=q+'|'+JSON.stringify(filters)+'|'+String(st.sortKey||'')+'|'+String(st.asc!==false)+'|'+cacheRevision;if(key===rowsCacheKey&&rowsCache)return rowsCache;let out=cache.actuaciones||[],nq=norm(q);if(nq)out=out.filter(r=>String(r.__ax_search||'').includes(nq));out=filterRows(TYPE,out);out=sortRows(TYPE,out);rowsCacheKey=key;rowsCache=out;return out;}
  function display(r,key,type){const v=r?.[key];if(v===null||v===undefined||v==='')return '';if(type==='currency')return money(v);if(type==='date')return displayDate(v);return String(v);}
  function row(r){return '<tr data-ax-row="'+Number(r.id)+'">'+F.map(([k,,t])=>{const v=display(r,k,t);return '<td data-ax-cell="'+esc(k)+'" title="'+esc(v)+'"><span class="ax-display'+(t==='currency'?' money':'')+(t==='textarea'?' observation':'')+'">'+esc(v)+'</span></td>';}).join('')+'</tr>';}
  function editCell(cell){if(cell.dataset.axEditing==='1'||cell.dataset.axCell==='tramite_en_curso')return;const tr=cell.closest('tr[data-ax-row]');if(!tr)return;const id=Number(tr.dataset.axRow),key=cell.dataset.axCell,def=F.find(x=>x[0]===key),rec=(cache.actuaciones||[]).find(x=>Number(x.id)===id);if(!def||!rec)return;cell.dataset.axEditing='1';const type=def[2],old=rec[key]??'';let editor;
    if(type==='select'){editor=document.createElement('select');editor.className='ax-cell-edit ax-cell-select';const vals=[...new Set((cache.actuaciones||[]).map(r=>String(r?.[key]??'').trim().toUpperCase()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));editor.innerHTML='<option value="">SELECCIONAR...</option>'+vals.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');editor.value=String(old??'').toUpperCase();editor.addEventListener('change',commit);}
    else{editor=type==='textarea'?document.createElement('textarea'):document.createElement('input');editor.className='ax-cell-edit'+(type==='currency'?' ax-cell-money':'')+(type==='date'?' ax-cell-date':'')+(type==='textarea'?' ax-cell-observation':'');editor.type='text';editor.inputMode=type==='currency'||type==='date'?'numeric':'text';editor.value=type==='currency'?(typeof moneyInput==='function'?moneyInput(old):old):type==='date'?(typeof displayDate==='function'?displayDate(old):old):String(old??'');if(type==='date'){editor.maxLength=10;editor.placeholder='DD-MM-AA';editor.addEventListener('input',()=>{if(typeof formatDateTyping==='function')editor.value=formatDateTyping(editor.value);});}editor.addEventListener('keydown',e=>{if(e.key==='Enter'&&type!=='textarea'){e.preventDefault();editor.blur();}if(e.ctrlKey&&String(e.key).toLowerCase()==='enter'&&type==='textarea'){e.preventDefault();editor.blur();}if(e.key==='Escape'){e.preventDefault();cancel();}});editor.addEventListener('blur',commit);}
    function cancel(){cell.dataset.axEditing='';cell.innerHTML='<span class="ax-display">'+esc(display(rec,key,type))+'</span>';}
    let committed=false;async function commit(){if(committed)return;committed=true;const fn=type==='date'?(window.updateInlineDate||window.updateInlineField):window.updateInlineField;if(typeof fn!=='function'){cancel();return;}const ok=await fn(TYPE,id,key,editor.value,editor);if(ok){rec[key]=type==='date'?(typeof isoFromDateInput==='function'?isoFromDateInput(editor.value):editor.value):type==='currency'?(typeof parseMoney==='function'?parseMoney(editor.value):editor.value):String(editor.value||'').trim().toUpperCase();cell.dataset.axEditing='';cell.innerHTML='<span class="ax-display">'+esc(display(rec,key,type))+'</span>';if(DATES.has(key))refreshTramite(rec);rowsCacheKey='';}else{committed=false;editor.focus();}}
    cell.innerHTML='';cell.appendChild(editor);editor.focus();if(editor.select)editor.select();
  }
  function bindEdit(){if(document.documentElement.dataset.axUltraEdit==='1')return;document.documentElement.dataset.axUltraEdit='1';document.addEventListener('click',e=>{if(!isAct())return;const cell=e.target.closest?.('#content td[data-ax-cell]');if(!cell||e.target.closest('input,select,textarea,.column-filter-panel,.filter-icon'))return;editCell(cell);},false);}
  function listFast(type){if(type!==TYPE)return false;const rows=getRows(),q=String(document.getElementById('search')?.value||'').trim();const html='<div class="toolbar"><button onclick="openModal(\'actuaciones\')">+ NUEVO</button><button class="alt" onclick="importXlsx(\'actuaciones\')">IMPORTAR XLSX</button><button class="alt" onclick="exportXlsx(\'actuaciones\')">EXPORTAR XLSX</button><button class="alt clear-filters-btn" onclick="clearAllFilters()">LIMPIAR FILTROS</button>'+(q?'<span class="sort-note">BUSCANDO: '+esc(q.toUpperCase())+'</span>':'')+'</div><div class="tablewrap"><table class="resizable-table actuaciones-expedientes-table ax-fast"><thead><tr>'+F.map(([k,l])=>sortHeader(TYPE,k,l)).join('')+'</tr></thead><tbody>'+(rows.length?rows.map(row).join(''):'<tr><td colspan="20" class="empty">NO HAY REGISTROS PARA EL FILTRO ACTUAL</td></tr>')+'</tbody></table></div>';$('content').innerHTML=html;bindEdit();if(typeof bindColumnResize==='function')bindColumnResize($('content'),TYPE);const table=$('content').querySelector('table');if(dataSignature!==window.__AX_WIDTH_DATA_SIGNATURE__&&typeof fitColumns==='function'){fitColumns($('content'));window.__AX_WIDTH_DATA_SIGNATURE__=dataSignature;}else if(table&&typeof applySavedColumnWidths==='function')applySavedColumnWidths(table,'actuaciones');return true;}
  const nativeList=window.list;window.list=function(type){if(type===TYPE)return listFast(type);return nativeList.apply(this,arguments);};
  function syncSearch(editor){const cell=editor?.closest?.('td[data-ax-cell]');if(!cell||!['nit','razon_social','expediente'].includes(cell.dataset.axCell))return;const r=(cache.actuaciones||[]).find(x=>Number(x.id)===Number(cell.closest('tr')?.dataset.axRow));if(r)r.__ax_search=['nit','razon_social','expediente'].map(k=>norm(r?.[k])).filter(Boolean).join(' | ');rowsCacheKey='';}
  function install(){if(window.__ACTUACIONES_ULTRA_20261010_8__)return;bindEdit();document.addEventListener('input',e=>{if(e.target?.matches?.('.ax-cell-edit'))syncSearch(e.target);},true);window.__ACTUACIONES_ULTRA_20261010_8__=true;window.__ACTUACIONES_ULTRA_VERSION__='20261010.8';}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,200));else setTimeout(install,200);
})();
