/* INVENTARIO DE CARTERA — EXPEDIENTES — VERSION 20261009.1 */
(function(){
  const VERSION="20261009.1";
  const FIELDS=[
    ["nit","NIT","nit"],["expediente","EXPEDIENTE","text"],["razon_social","RAZON SOCIAL","text"],
    ["anio","AÑO","text"],["periodo","PERIODO","text"],["obligacion","OBLIGACIÓN","text"],
    ["tipo_obl","TIPO OBL","text"],["cuantia","CUANTÍA","currency"],["fecha_prescripcion","FECHA PRESCRIPCIÓN","date"],
    ["aplicativo","APLICATIVO","text"],["gestion","GESTIÓN","gestion"],["estado","ESTADO","estado"],
    ["fecha_aviso_cobro","FECHA AVISO DE COBRO","date"],["fecha_opp","FECHA OPP","date"],
    ["fecha_embargo","FECHA EMBARGO","date"],["fecha_desembargo","FECHA DESEMBARGO","date"],
    ["fecha_investigacion_bienes","FECHA INVESTIGACIÓN DE BIENES","date"],
    ["fecha_mandamiento_pago","FECHA MANDAMIENTO DE PAGO","date"],["observaciones","OBSERVACIONES","textarea"]
  ];
  const GESTION_BASE=["PENDIENTE","EN PROCESO","TERMINADO","DEVUELTO"];
  const ESTADO_BASE=["PENDIENTE","EN PROCESO","TERMINADO","DEVUELTO"];
  const TYPE="expedientes";
  function norm(v){return String(v??"").trim().toUpperCase();}
  function dateIso(v){if(v instanceof Date&&!isNaN(v))return v.toISOString().slice(0,10);if(typeof v==="number"&&Number.isFinite(v))return new Date(Math.round((v-25569)*86400000)).toISOString().slice(0,10);return isoFromDateInput(String(v??""))||(/^\d{4}-\d{2}-\d{2}$/.test(String(v))?String(v):"");}
  function keyFor(r){return [norm(r.expediente),norm(r.anio),norm(r.periodo),norm(r.obligacion),norm(r.tipo_obl),String(r.cuantia??"").trim(),dateIso(r.fecha_prescripcion),norm(r.aplicativo)].join("|");}
  function uniqueOptions(field){const base=field==="gestion"?GESTION_BASE:ESTADO_BASE,vals=new Set(base);(cache.expedientes||[]).forEach(r=>{const v=norm(r[field]);if(v)vals.add(v);});return [...vals];}
  function cell(r,f){const [k,label,type]=f,v=r[k]??"";if(type==="currency")return money(v);if(type==="date")return displayDate(String(v||"").slice(0,10));if(type==="gestion"||type==="estado"){const opts=uniqueOptions(k);return '<select class="exp-inline-'+k+'" data-exp-id="'+r.id+'" data-exp-field="'+k+'">'+opts.map(x=>'<option value="'+esc(x)+'" '+(norm(v)===x?'selected':'')+'>'+esc(x)+'</option>').join("")+'</select>';}if(type==="textarea")return '<input class="exp-inline-text" data-exp-id="'+r.id+'" data-exp-field="'+k+'" value="'+esc(v)+'">';return esc(v);}
  function renderRows(rows){return rows.map(r=>'<tr data-expediente="'+esc(r.expediente||"")+'">'+FIELDS.map(f=>'<td>'+cell(r,f)+'</td>').join("")+'<td class="actions"><button onclick="openModal(\'expedientes\','+r.id+')">EDITAR</button><button onclick="del(\'expedientes\','+r.id+')">ELIMINAR</button></td></tr>').join("");}
  function header(f){const [k,label]=f,st=tableState.expedientes||{},active=st.sortKey===k,arrow=active?(st.asc?" ↑":" ↓"):"";return '<th data-column-key="'+k+'"><div class="header-tools"><button type="button" class="sort-header '+(active?"active":"")+'" data-exp-sort="'+k+'">'+esc(label)+arrow+'</button><button type="button" class="filter-icon" data-exp-filter="'+k+'" title="FILTRAR '+esc(label)+'"><svg class="funnel-icon" viewBox="0 0 24 24"><path d="M3 5h18l-7 8v5l-4 2v-7L3 5z"></path></svg></button><div class="column-filter-panel" data-exp-panel="'+k+'"><div class="column-filter-title">'+esc(label)+'</div><input class="column-filter-input" data-exp-filter-input="'+k+'" placeholder="BUSCAR..."><button class="column-filter-apply" data-exp-filter-apply="'+k+'">APLICAR</button><button class="column-filter-clear" data-exp-filter-clear="'+k+'">LIMPIAR FILTRO</button></div></div><span class="column-resizer" title="AJUSTAR ANCHO"></span></th>';}
  function applyFilters(rows){const fs=tableState.expedientes?.filters||{};return rows.filter(r=>Object.entries(fs).every(([k,f])=>!f||!String(f.text||"")||String(r[k]??"").toUpperCase().includes(String(f.text).toUpperCase())));}
  function sortRowsExp(rows){const st=tableState.expedientes||{};if(!st.sortKey)return rows;const k=st.sortKey,asc=st.asc!==false;return [...rows].sort((a,b)=>{let av=a[k]??"",bv=b[k]??"";if(k==="cuantia"){av=Number(av||0);bv=Number(bv||0);return asc?av-bv:bv-av;}const c=String(av).toUpperCase().localeCompare(String(bv).toUpperCase(),"es",{numeric:true,sensitivity:"base"});return asc?c:-c;});}
  function bind(){const root=$("content");root.querySelectorAll("[data-exp-sort]").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.expSort,st=tableState.expedientes;if(st.sortKey===k)st.asc=st.asc===true?false:true;else{st.sortKey=k;st.asc=true;}list(TYPE);}));root.querySelectorAll("[data-exp-filter]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();root.querySelectorAll(".column-filter-panel.open").forEach(p=>p.classList.remove("open"));root.querySelector('[data-exp-panel="'+CSS.escape(b.dataset.expFilter)+'"]')?.classList.add("open");}));root.querySelectorAll("[data-exp-filter-apply]").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.expFilterApply,p=root.querySelector('[data-exp-panel="'+CSS.escape(k)+'"]');tableState.expedientes.filters[k]={text:p.querySelector("input")?.value||""};list(TYPE);}));root.querySelectorAll("[data-exp-filter-clear]").forEach(b=>b.addEventListener("click",()=>{delete tableState.expedientes.filters[b.dataset.expFilterClear];list(TYPE);}));root.querySelectorAll(".exp-inline-gestion,.exp-inline-estado,.exp-inline-text").forEach(el=>{if(el.dataset.bound==="1")return;el.dataset.bound="1";const save=async()=>{const id=Number(el.dataset.expId),field=el.dataset.expField,value=field==="gestion"||field==="estado"?norm(el.value):el.value.toUpperCase(),r=(cache.expedientes||[]).find(x=>Number(x.id)===id);if(!r)return;const old=r[field];r[field]=value;const q=await db.from("cartera_expedientes").update({[field]:value||null}).eq("id",id);if(q.error){r[field]=old;alert("NO SE PUDO GUARDAR: "+q.error.message);return;}if(field==="estado"||field==="gestion")await syncInicio(r.expediente);};el.addEventListener(field==="estado"||field==="gestion"?"change":"blur",save);});bindColumnResize(root,TYPE);}
  async function syncInicio(expediente){const exp=norm(expediente);if(!exp)return;const rel=(cache.expedientes||[]).filter(r=>norm(r.expediente)===exp);if(!rel.length)return;const allDone=rel.every(r=>norm(r.estado)==="TERMINADO"||norm(r.gestion)==="TERMINADO"),state=allDone?"TERMINADO":"PROCESO";const q=await db.from("cartera_inicio").update({estado:state}).eq("expediente",exp);if(q.error)console.error("SYNC INICIO",q.error);const ir=(cache.inicio||[]).find(r=>norm(r.expediente)===exp);if(ir)ir.estado=state;}
  async function finishFromInicio(expediente){const exp=norm(expediente),rel=(cache.expedientes||[]).filter(r=>norm(r.expediente)===exp),ids=rel.map(r=>r.id);if(!ids.length)return;const q=await db.from("cartera_expedientes").update({estado:"TERMINADO",gestion:"TERMINADO"}).in("id",ids);if(q.error)throw q.error;rel.forEach(r=>{r.estado="TERMINADO";r.gestion="TERMINADO";});}
  async function importExpedientes(file){const data=await file.arrayBuffer(),wb=XLSX.read(data,{cellDates:true}),sheet=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{defval:null,raw:true}),existing=new Set((cache.expedientes||[]).map(keyFor));let inserted=0,skipped=0;const payload=[];for(const row of rows){const o={};FIELDS.forEach(([k,label])=>{const hit=Object.keys(row).find(h=>norm(h)===norm(label)||norm(h)===norm(k));if(hit!==undefined)o[k]=row[hit];});if(!o.expediente){skipped++;continue;}o.nit=String(o.nit??"").trim();o.razon_social=norm(o.razon_social);o.anio=String(o.anio??"").trim();o.periodo=String(o.periodo??"").trim();o.obligacion=norm(o.obligacion);o.tipo_obl=norm(o.tipo_obl);o.aplicativo=norm(o.aplicativo);o.cuantia=parseMoney(o.cuantia);o.fecha_prescripcion=dateIso(o.fecha_prescripcion);["fecha_aviso_cobro","fecha_opp","fecha_embargo","fecha_desembargo","fecha_investigacion_bienes","fecha_mandamiento_pago"].forEach(k=>o[k]=dateIso(o[k])||null);o.gestion=norm(o.gestion)||"EN PROCESO";o.estado=norm(o.estado)||"EN PROCESO";o.observaciones=norm(o.observaciones)||null;const key=keyFor(o);if(existing.has(key)){skipped++;continue;}existing.add(key);payload.push({...o,user_id:currentUser.id,import_key:key});}for(let i=0;i<payload.length;i+=50){const q=await db.from("cartera_expedientes").insert(payload.slice(i,i+50));if(q.error)throw q.error;inserted+=Math.min(50,payload.length-i);}await load();const affected=[...new Set(payload.map(x=>x.expediente))];for(const exp of affected)await syncInicio(exp);return {inserted,skipped,affected};}
  window.importXlsx=async function(type){if(type!==TYPE)return alert("EL IMPORTADOR GENERAL SE CONSERVA PARA LAS DEMÁS PESTAÑAS.");const input=document.createElement("input");input.type="file";input.accept=".xlsx,.xls";input.onchange=async()=>{if(!input.files[0])return;try{const r=await importExpedientes(input.files[0]);render();alert("IMPORTACIÓN COMPLETADA. NUEVOS: "+r.inserted+" | YA EXISTENTES/OMITIDOS: "+r.skipped);}catch(e){console.error(e);alert("ERROR EN IMPORTACIÓN: "+(e.message||e));}};input.click();};
  const originalList=window.list;window.list=function(type){if(type!==TYPE)return originalList(type);const raw=Array.isArray(cache.expedientes)?cache.expedientes:[],rows=sortRowsExp(applyFilters(raw)),heads=FIELDS.map(header).join("");$("content").innerHTML='<div class="toolbar"><button onclick="openModal(\'expedientes\')">+ NUEVO</button><button class="alt" onclick="importXlsx(\'expedientes\')">IMPORTAR XLSX</button><button class="alt" onclick="exportXlsx(\'expedientes\')">EXPORTAR XLSX</button><button class="alt clear-filters-btn" onclick="tableState.expedientes.filters={};list(\'expedientes\')">LIMPIAR FILTROS</button><span class="muted">'+rows.length+' REGISTROS</span></div><div class="card-body expedientes-card"><div class="tablewrap"><table class="resizable-table expedientes-table"><thead><tr>'+heads+'<th data-column-key="__actions"><div class="header-tools"><button type="button" class="sort-header">ACCIONES</button></div></th></tr></thead><tbody>'+(renderRows(rows)||'<tr><td colspan="20" class="empty">NO HAY REGISTROS</td></tr>')+'</tbody></table></div></div>';bind();};
  if(defs?.expedientes)defs.expedientes.fields=FIELDS.map(([k,l,t])=>[k,l,t==="gestion"?"gestion":t==="estado"?"status":t]);
  let wrapped=false;const wrapInicio=()=>{if(wrapped||typeof window.updateInicio!=="function")return;const original=window.updateInicio;wrapped=true;window.updateInicio=async function(id,patch){const row=(cache.inicio||[]).find(x=>Number(x.id)===Number(id));await original(id,patch);if(norm(patch?.estado)==="TERMINADO"&&row){try{await finishFromInicio(row.expediente);}catch(e){console.error("CIERRE DESDE INICIO",e);alert("NO FUE POSIBLE ACTUALIZAR TODAS LAS OBLIGACIONES: "+e.message);}}if(norm(patch?.estado)!==="TERMINADO"&&row?.expediente)await syncInicio(row.expediente);};};const timer=setInterval(()=>{wrapInicio();if(wrapped)clearInterval(timer);},250);
  const style=document.createElement("style");style.textContent='.expedientes-card{height:450px;min-height:450px;overflow:hidden}.expedientes-card .tablewrap{height:calc(450px - 16px);overflow:auto;position:relative}.expedientes-card .expedientes-table{width:max-content;min-width:100%}.expedientes-card .expedientes-table th,.expedientes-card .expedientes-table td{white-space:nowrap;vertical-align:middle}.expedientes-card .expedientes-table thead th{position:sticky;top:0;z-index:40;background:#eaf5fc;color:#285a7d}.expedientes-card .header-tools{position:relative;display:flex;align-items:center;gap:2px;min-width:100%}.expedientes-card .sort-header{flex:1;min-width:0;padding:3px 5px;background:transparent;color:#285a7d;border:0;border-radius:5px;font-size:11px;font-weight:700;text-align:left;white-space:nowrap;cursor:pointer}.expedientes-card .sort-header:hover,.expedientes-card .sort-header.active{background:#dff2fc;color:#0b628f}.expedientes-card .filter-icon{width:26px;height:26px;flex:0 0 26px;border:1px solid transparent!important;background:transparent!important;color:#285a7d!important;display:flex;align-items:center;justify-content:center;cursor:pointer}.expedientes-card .column-filter-panel{position:absolute;display:none;top:calc(100% + 4px);right:0;min-width:210px;padding:10px;background:#fff;border:1px solid #c9dce8;border-radius:9px;box-shadow:0 12px 28px #16466b2b;z-index:100}.expedientes-card .column-filter-panel.open{display:flex;flex-direction:column;gap:7px}.expedientes-card .column-filter-input{height:30px;border:1px solid #c9dce8;border-radius:6px;padding:5px 7px}.expedientes-card select,.expedientes-card input{height:32px;box-sizing:border-box;border:1px solid #d4dbe3;border-radius:6px;background:#fff;padding:6px 8px;font:inherit;color:inherit}.expedientes-card td:nth-child(19) input{min-width:220px}.expedientes-card td:nth-child(8){text-align:right}.expedientes-card td{padding-top:5px;padding-bottom:5px}.expedientes-card tbody tr:hover>td{background:#f6fbfe}.expedientes-card .column-resizer{z-index:60}';document.head.appendChild(style);
})();
