/* INVENTARIO DE CARTERA — EXPEDIENTES ULTRA UI v20261009.2 */
(function(){
  const VERSION='20261009.2';
  if(window.__EXPEDIENTES_ULTRA_UI__===VERSION)return;
  window.__EXPEDIENTES_ULTRA_UI__=VERSION;
  const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase().replace(/\s+/g,' ');
  const dateDisplay=v=>{const s=String(v??'').slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const [y,m,d]=s.split('-');return d+'/'+m+'/'+y;}return String(v??'');};
  const dateIso=v=>{if(typeof isoFromDateInput==='function')return isoFromDateInput(v)||'';const s=String(v??'').replace(/\D/g,'');if(s.length===6)return '20'+s.slice(4,6)+'-'+s.slice(2,4)+'-'+s.slice(0,2);if(s.length===8)return s.slice(4,8)+'-'+s.slice(2,4)+'-'+s.slice(0,2);return '';};
  const F=[
    ['nit','NIT','text',115],['expediente','EXPEDIENTE','text',135],['razon_social','RAZÓN SOCIAL','text',330],['anio','AÑO','text',75],['periodo','PERIODO','text',85],['obligacion','OBLIGACIÓN','select-obligacion',300],['tipo_obl','TIPO OBL','select-tipo',105],['cuantia','CUANTÍA','currency',135],['fecha_prescripcion','FECHA PRESCRIPCIÓN','date',175],['aplicativo','APLICATIVO','select-aplicativo',110],['gestion','GESTIÓN','gestion',125],['estado','ESTADO','estado',220],['fecha_aviso_cobro','FECHA AVISO DE COBRO','date',160],['fecha_opp','FECHA OPP','date',140],['fecha_embargo','FECHA EMBARGO','date',155],['fecha_desembargo','FECHA DESEMBARGO','date',165],['fecha_investigacion_bienes','FECHA INVESTIGACIÓN DE BIENES','date',190],['fecha_mandamiento_pago','FECHA MANDAMIENTO DE PAGO','date',190],['observaciones','OBSERVACIONES','textarea',1410]
  ];
  const BASE={obligacion:['RENTA','IVA','RETENCIÓN','HIPOCONSUMO','PATRIMONIO','RENTA CREE','VENTAS','CONSUMO','RETENCIÓN CREE','RIQUEZA','GMF','SANCION','SIMPLE','OTROS'],tipo_obl:['LO','LFA','PL','LP','CP','FA'],aplicativo:['OBLIGA','PAC'],gestion:['PENDIENTE','EN PROCESO','TERMINADO','DEVUELTO'],estado:['AVISO DE COBRO','OFICIO PERSUASIVO PENALIZABLE','OPP','EMBARGO','DESEMBARGO','INVESTIGACIÓN DE BIENES','MANDAMIENTO DE PAGO']};
  let optionCache={};
  function optionValues(field){if(optionCache[field])return optionCache[field];const set=new Map((BASE[field]||[]).map(v=>[norm(v),v]));(cache?.expedientes||[]).forEach(r=>{const v=String(r?.[field]??'').trim();if(v&&!set.has(norm(v)))set.set(norm(v),v)});return optionCache[field]=[...set.values()].sort((a,b)=>String(a).localeCompare(String(b),'es',{numeric:true,sensitivity:'base'}));}
  function selectCell(field,current,id){const cur=String(current??'').trim();let h='<option value="'+esc(cur)+'" selected>'+esc(cur||'SELECCIONAR...')+'</option>';return '<select class="exp-ultra-select exp-ultra-'+field+'" data-ultra-id="'+id+'" data-ultra-field="'+field+'" data-loaded="0">'+h+'</select>';}
  function val(r,f){const [k,,type]=f,v=r?.[k]??'';if(type==='currency')return typeof money==='function'?money(v):String(v);if(type==='date')return '<div class="exp-ultra-date"><input class="exp-ultra-date-text" data-ultra-id="'+r.id+'" data-ultra-field="'+k+'" value="'+esc(dateDisplay(v))+'" inputmode="numeric" maxlength="10" placeholder="DD/MM/AA"><input class="exp-ultra-date-picker" type="date" value="'+esc(String(v||'').slice(0,10))+'" tabindex="-1"></div>';if(type==='textarea')return '<input class="exp-ultra-obs" data-ultra-id="'+r.id+'" data-ultra-field="'+k+'" value="'+esc(v)+'" placeholder="OBSERVACIONES">';if(type.startsWith('select-')||type==='gestion'||type==='estado')return selectCell(k,v,r.id);return esc(v);}
  function row(r){return '<tr data-ultra-exp="'+esc(r.expediente||'')+'">'+F.map(f=>'<td>'+val(r,f)+'</td>').join('')+'</tr>';}
  function state(){tableState.expedientes=tableState.expedientes||{filters:{}};tableState.expedientes.filters=tableState.expedientes.filters||{};return tableState.expedientes;}
  function filtered(){let rows=[...(cache.expedientes||[])],s=state();for(const [k,f] of Object.entries(s.filters||{})){if(!f)continue;if(k==='estado'||k==='gestion'){const x=norm(f.value);if(x)rows=rows.filter(r=>norm(r?.[k])===x)}else if(k==='fecha_prescripcion'){if(f.from)rows=rows.filter(r=>String(r?.[k]||'').slice(0,10)>=f.from);if(f.to)rows=rows.filter(r=>String(r?.[k]||'').slice(0,10)<=f.to)}else if(f.text)rows=rows.filter(r=>norm(r?.[k]).includes(norm(f.text)));}if(s.sortKey){const k=s.sortKey,asc=s.asc!==false;rows.sort((a,b)=>{let x=a?.[k]??'',y=b?.[k]??'';if(k==='cuantia'){x=Number(x||0);y=Number(y||0);return asc?x-y:y-x}const c=String(x).localeCompare(String(y),'es',{numeric:true,sensitivity:'base'});return asc?c:-c})}return rows;}
  function panel(k,label){const f=state().filters?.[k]||{};let body;if(k==='estado'||k==='gestion')body='<select data-ultra-filter-value="'+k+'"><option value="">TODOS</option>'+optionValues(k).map(v=>'<option value="'+esc(v)+'" '+(norm(f.value)===norm(v)?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select>';else if(k==='fecha_prescripcion')body='<input data-ultra-from="'+k+'" placeholder="DESDE DD/MM/AA" value="'+esc(f.from?dateDisplay(f.from):'')+'"><input data-ultra-to="'+k+'" placeholder="HASTA DD/MM/AA" value="'+esc(f.to?dateDisplay(f.to):'')+'">';else body='<input data-ultra-filter-text="'+k+'" placeholder="BUSCAR..." value="'+esc(f.text||'')+'">';return '<div class="exp-ultra-panel" data-ultra-panel="'+k+'"><strong>'+esc(label)+'</strong>'+body+'<button data-ultra-apply="'+k+'">APLICAR</button><button data-ultra-clear="'+k+'">LIMPIAR FILTRO</button></div>';}
  function header(f){const [k,label]=f,s=state(),active=s.sortKey===k,has=Object.values(s.filters?.[k]||{}).some(v=>String(v??'')!=='');return '<th data-column-key="'+k+'" data-ultra-key="'+k+'"><div class="exp-ultra-head"><button class="exp-ultra-sort '+(active?'active':'')+'" data-ultra-sort="'+k+'">'+esc(label)+(active?(s.asc?' ↑':' ↓'):'')+'</button><button class="exp-ultra-filter '+(has?'active':'')+'" data-ultra-filter="'+k+'" aria-label="FILTRAR '+esc(label)+'">⌄</button>'+panel(k,label)+'</div><span class="column-resizer" title="AJUSTAR ANCHO"></span></th>';}
  function skeleton(){return '<div class="expedientes-ultra"><div class="toolbar"><button onclick="openModal(\'expedientes\')">+ NUEVO</button><button class="alt" onclick="importXlsx(\'expedientes\')">IMPORTAR XLSX</button><button class="alt" onclick="exportXlsx(\'expedientes\')">EXPORTAR XLSX</button><button class="alt" onclick="tableState.expedientes.filters={};renderBody()">LIMPIAR FILTROS</button><span class="muted" data-ultra-count></span></div><div class="card-body expedientes-card"><div class="tablewrap"><table class="resizable-table expedientes-table"><colgroup data-ultra-cols>'+F.map(()=>'<col>').join('')+'</colgroup><thead><tr>'+F.map(header).join('')+'</tr></thead><tbody></tbody></table></div></div></div>';}
  function applyWidths(table){F.forEach((f,i)=>{const w=f[3];const c=table.querySelectorAll('thead th:nth-child('+(i+1)+'),tbody td:nth-child('+(i+1)+')');const col=table.querySelector('colgroup').children[i];if(col)col.style.width=w+'px';c.forEach(x=>{x.style.width=w+'px';x.style.minWidth=w+'px';x.style.maxWidth=w+'px'});});table.style.tableLayout='fixed';table.style.width='max-content';}
  function renderBody(){const root=$('.expedientes-ultra');if(!root)return;const tbody=root.querySelector('tbody'),rows=filtered();const box=document.createElement('tbody');box.innerHTML=rows.length?rows.map(row).join(''):'<tr><td colspan="19" class="empty">NO HAY REGISTROS</td></tr>';tbody.replaceChildren(...box.children);root.querySelector('[data-ultra-count]').textContent=rows.length+' REGISTROS';applyWidths(root.querySelector('table'));bindBody(root);updateHeaderState(root);}
  function updateHeaderState(root){const s=state();root.querySelectorAll('[data-ultra-sort]').forEach(b=>{const k=b.dataset.ultraSort,active=s.sortKey===k;b.classList.toggle('active',active);b.textContent=b.textContent.replace(/\s[↑↓]$/,'')+(active?(s.asc?' ↑':' ↓'):'')});root.querySelectorAll('[data-ultra-filter]').forEach(b=>{const k=b.dataset.ultraFilter;b.classList.toggle('active',Object.values(s.filters?.[k]||{}).some(v=>String(v??'')!==''))});}
  function populateSelect(el){if(el.dataset.loaded==='1')return;const cur=el.value,vals=optionValues(el.dataset.ultraField);el.innerHTML='<option value="">SELECCIONAR...</option>'+vals.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');el.value=vals.find(v=>norm(v)===norm(cur))||cur;el.dataset.loaded='1';}
  async function save(el,value){const id=Number(el.dataset.ultraId),field=el.dataset.ultraField,row=(cache.expedientes||[]).find(r=>Number(r.id)===id);if(!row)return;const old=row[field],next=String(value??'').trim().toUpperCase();row[field]=next||null;el.disabled=true;try{const q=await db.from('cartera_expedientes').update({[field]:next||null}).eq('id',id).eq('user_id',currentUser.id);if(q.error)throw q.error;if((field==='estado'||field==='gestion')&&typeof window.updateInicio==='function')await window.updateInicio(row.expediente);}catch(e){row[field]=old;el.value=old||'';console.error(e)}finally{el.disabled=false;}}
  function bindBody(root){root.querySelectorAll('.exp-ultra-select').forEach(el=>{el.addEventListener('focus',()=>populateSelect(el));el.addEventListener('change',()=>save(el,el.value));});root.querySelectorAll('.exp-ultra-obs').forEach(el=>el.addEventListener('blur',()=>save(el,el.value)));root.querySelectorAll('.exp-ultra-date-text').forEach(el=>el.addEventListener('blur',()=>{const x=dateIso(el.value);if(x)save(el,x)}));root.querySelectorAll('.exp-ultra-date-picker').forEach(el=>el.addEventListener('change',()=>{const x=el.parentElement.querySelector('.exp-ultra-date-text');x.value=dateDisplay(el.value);save(x,el.value)}));}
  function measureFieldWidth(field){const idx=F.findIndex(x=>x[0]===field),def=F[idx]?.[3]||120,rows=cache?.expedientes||[];if(idx<0)return def;const header=String(F[idx][1]||'');let max=header.length;rows.forEach(r=>{let v=r?.[field]??'';if(F[idx][2]==='date')v=dateDisplay(v);max=Math.max(max,String(v).length)});const approx=Math.ceil(max*7.1+24);return Math.max(Math.min(approx,field==='razon_social'?420:field==='observaciones'?1800:(field.includes('fecha_')||field==='fecha_prescripcion'?220:field==='obligacion'?320:240)),def);}
  function setUltraWidth(table,idx,width){const w=Math.round(width),col=table.querySelector('colgroup').children[idx];if(col)col.style.width=w+'px';table.querySelectorAll('thead th:nth-child('+(idx+1)+'),tbody td:nth-child('+(idx+1)+')').forEach(c=>{c.style.width=w+'px';c.style.minWidth=w+'px';c.style.maxWidth=w+'px';});}
  function bindUltraResize(root){const table=root.querySelector('table');if(!table)return;root.querySelectorAll('.column-resizer').forEach((resizer,idx)=>{if(resizer.dataset.ultraBound==='1')return;resizer.dataset.ultraBound='1';let startX=0,startW=0;resizer.addEventListener('dblclick',e=>{e.preventDefault();e.stopPropagation();setUltraWidth(table,idx,measureFieldWidth(F[idx][0]));});resizer.addEventListener('mousedown',e=>{e.preventDefault();startX=e.clientX;startW=table.querySelector('colgroup').children[idx]?.getBoundingClientRect().width||F[idx][3];const move=x=>setUltraWidth(table,idx,Math.max(70,startW+(x.clientX-startX)));const up=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up)};document.addEventListener('mousemove',move);document.addEventListener('mouseup',up);});});}
  function bindHeaders(root){root.querySelectorAll('[data-ultra-sort]').forEach(b=>b.addEventListener('click',()=>{const s=state(),k=b.dataset.ultraSort;s.sortKey===k?s.asc=!s.asc:(s.sortKey=k,s.asc=true);renderBody()}));root.querySelectorAll('[data-ultra-filter]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const p=root.querySelector('[data-ultra-panel="'+CSS.escape(b.dataset.ultraFilter)+'"]');root.querySelectorAll('.exp-ultra-panel.open').forEach(x=>x!==p&&x.classList.remove('open'));p.classList.toggle('open')}));root.querySelectorAll('[data-ultra-apply]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.ultraApply,p=b.closest('.exp-ultra-panel'),s=state();if(k==='estado'||k==='gestion')s.filters[k]={value:p.querySelector('[data-ultra-filter-value]')?.value||''};else if(k==='fecha_prescripcion'){const a=dateIso(p.querySelector('[data-ultra-from]')?.value||''),z=dateIso(p.querySelector('[data-ultra-to]')?.value||'');s.filters[k]={};if(a)s.filters[k].from=a;if(z)s.filters[k].to=z}else s.filters[k]={text:p.querySelector('[data-ultra-filter-text]')?.value||''};p.classList.remove('open');renderBody()}));root.querySelectorAll('[data-ultra-clear]').forEach(b=>b.addEventListener('click',()=>{delete state().filters[b.dataset.ultraClear];renderBody()}));}
  function installStyle(){if($('#expedientes-ultra-style'))return;const s=document.createElement('style');s.id='expedientes-ultra-style';s.textContent=`
  .expedientes-ultra .expedientes-card{height:450px;min-height:450px;overflow:hidden}.expedientes-ultra .tablewrap{height:calc(450px - 16px);overflow:auto;position:relative}.expedientes-ultra .expedientes-table{table-layout:fixed!important;width:max-content!important;min-width:0!important}.expedientes-ultra .expedientes-table th,.expedientes-ultra .expedientes-table td{box-sizing:border-box;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.expedientes-ultra .expedientes-table thead th{position:sticky;top:0;z-index:30;background:#eaf5fc;padding:5px 7px!important;overflow:visible}.exp-ultra-head{position:relative;display:flex;align-items:center;gap:3px;width:100%;height:26px}.exp-ultra-sort{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border:0;background:transparent;color:#285a7d;font-size:11px;font-weight:800;text-align:left;padding:3px 4px;cursor:pointer}.exp-ultra-sort.active,.exp-ultra-sort:hover{background:#dff2fc;border-radius:5px}.exp-ultra-filter{width:25px;height:25px;flex:0 0 25px;border:0;border-radius:5px;background:transparent;color:#285a7d;font-size:18px;line-height:18px;cursor:pointer}.exp-ultra-filter.active,.exp-ultra-filter:hover{background:#dff2fc}.exp-ultra-panel{display:none;position:absolute;right:0;top:31px;width:250px;max-width:calc(100vw - 20px);padding:9px;background:#fff;border:1px solid #c9dce8;border-radius:8px;box-shadow:0 10px 24px #16466b2b;z-index:100;flex-direction:column;gap:6px}.exp-ultra-panel.open{display:flex}.exp-ultra-panel strong{font-size:10px;color:#285a7d}.exp-ultra-panel input,.exp-ultra-panel select,.exp-ultra-panel button{height:29px;box-sizing:border-box;border:1px solid #c9dce8;border-radius:6px;background:#fff;padding:4px 7px;font-size:10px}.exp-ultra-panel button{font-weight:800;cursor:pointer}.expedientes-ultra tbody td{padding:4px 7px!important;height:32px}.exp-ultra-select,.exp-ultra-obs,.exp-ultra-date-text{width:100%;min-width:0;max-width:100%;height:29px;box-sizing:border-box;border:1px solid #d4dbe3;border-radius:6px;background:#fff;padding:4px 7px;font:inherit}.exp-ultra-date{display:flex;gap:5px;width:100%}.exp-ultra-date-text{flex:1;min-width:0}.exp-ultra-date-picker{width:38px;min-width:38px;height:29px;border:1px solid #d4dbe3;border-radius:6px;background:#fff;padding:2px}.exp-ultra-select:focus,.exp-ultra-obs:focus,.exp-ultra-date-text:focus{outline:2px solid #cfe8f6;outline-offset:-1px}.expedientes-ultra .column-resizer{cursor:col-resize!important}
  `;document.head.appendChild(s);}
  function render(){const c=$('#content');if(!c)return;c.innerHTML=skeleton();const root=$('.expedientes-ultra'),table=root.querySelector('table');applyWidths(table);bindHeaders(root);renderBody();bindUltraResize(root);if(typeof bindColumnResize==='function')bindColumnResize(root,'expedientes');}
  function install(){if(typeof window.list!=='function'||typeof cache==='undefined'||typeof tableState==='undefined')return false;if(window.__EXPEDIENTES_ULTRA_BOUND__)return true;window.__EXPEDIENTES_ULTRA_BOUND__=true;const old=window.list;window.__EXPEDIENTES_ULTRA_ORIGINAL_LIST__=old;window.list=function(type){return type==='expedientes'?render():old(type)};window.expUltraRender=render;if(String(view||'')==='expedientes')render();return true;}
  installStyle();let n=0;const t=setInterval(()=>{if(install()||++n>100)clearInterval(t)},50);
})();
