/* INVENTARIO DE CARTERA — TOOLBAR INICIO — VERSION 20261009.8 */
(function(){
  const TOOLBAR_VERSION="20261009.8";
  const ESTADOS=["PENDIENTE","PROCESO","TERMINADO","DEVUELTO"];
  const norm=v=>String(v??"").trim().toUpperCase();
  const toIso=v=>{if(v===null||v===undefined||v==="")return "";if(typeof v==="number"&&window.XLSX?.SSF){try{const d=XLSX.SSF.parse_date_code(v);if(d?.y&&d?.m&&d?.d)return `${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}`;}catch{}}const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);if(/^\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}$/.test(s)||/^\d{6,8}$/.test(s))return isoFromDateInput(s);return "";};
  function ensureStyle(){if(document.getElementById("inicio-toolbar-style"))return;const style=document.createElement("style");style.id="inicio-toolbar-style";style.textContent=`
      .inicio-card{position:relative!important;box-sizing:border-box!important;}
      .inicio-card>.toolbar.inicio-toolbar{position:absolute!important;top:16px!important;left:28px!important;right:28px!important;width:auto!important;margin:0!important;display:flex!important;align-items:center!important;gap:10px!important;flex-wrap:nowrap!important;z-index:80!important;}
      .inicio-toolbar button{white-space:nowrap!important;}
      .inicio-card .inicio-scroll-wrap{margin-top:60px!important;width:100%!important;overflow-x:auto!important;overflow-y:auto!important;height:calc(450px - 78px)!important;max-height:none!important;position:relative!important;z-index:21!important;scrollbar-gutter:stable!important;}
      .inicio-card .inicio-scroll-wrap .inicio-table{min-width:1245px!important;width:max-content!important;}
      .inicio-card .inicio-table th:nth-child(5),.inicio-card .inicio-table td:nth-child(5){min-width:195px!important;width:195px!important;}
      .inicio-card .inicio-status-edit{min-width:175px!important;width:100%!important;height:32px!important;box-sizing:border-box!important;padding:0 30px 0 10px!important;font-size:11px!important;line-height:30px!important;font-family:inherit!important;white-space:nowrap!important;text-overflow:clip!important;overflow:visible!important;vertical-align:middle!important;display:block!important;}
      .inicio-card .inicio-table td:nth-child(5){padding-top:3px!important;padding-bottom:3px!important;vertical-align:middle!important;}
      .inicio-card .inicio-status-edit.gestion-status-pendiente{background:#fff1f1!important;border-color:#e8c2c2!important;color:#8b3d3d!important;}
      .inicio-card .inicio-status-edit.gestion-status-proceso{background:#fff7ea!important;border-color:#ead7b5!important;color:#8a5a16!important;}
      .inicio-card .inicio-status-edit.gestion-status-terminado{background:#eef8f0!important;border-color:#c7dfcb!important;color:#356b42!important;}
      .inicio-card .inicio-status-edit.gestion-status-devuelto{background:#f3f0ff!important;border-color:#d5ccef!important;color:#5d4a91!important;}
      .inicio-card .inicio-table tbody tr.gestion-row-pendiente>td{background:#fff1f1!important;}
      .inicio-card .inicio-table tbody tr.gestion-row-proceso>td{background:#fff7ea!important;}
      .inicio-card .inicio-table tbody tr.gestion-row-terminado>td{background:#eef8f0!important;}
      .inicio-card .inicio-table tbody tr.gestion-row-devuelto>td{background:#f3f0ff!important;}
      .inicio-card .inicio-table tbody tr.gestion-row-pendiente:hover>td{background:#ffebeb!important;}
      .inicio-card .inicio-table tbody tr.gestion-row-proceso:hover>td{background:#fff2df!important;}
      .inicio-card .inicio-table tbody tr.gestion-row-terminado:hover>td{background:#e7f4ea!important;}
      .inicio-card .inicio-table tbody tr.gestion-row-devuelto:hover>td{background:#eee9ff!important;}
      .inicio-card .inicio-scroll-wrap::-webkit-scrollbar{height:14px;width:12px;}
      .inicio-card .inicio-scroll-wrap::-webkit-scrollbar-track{background:#edf3f7;border-radius:8px;}
      .inicio-card .inicio-scroll-wrap::-webkit-scrollbar-thumb{background:#9eabb5;border-radius:8px;border:3px solid #edf3f7;}
      .inicio-card .inicio-scroll-wrap::-webkit-scrollbar-thumb:hover{background:#7f8d98;}
      .inicio-nuevo-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 12px}.inicio-nuevo-grid .full{grid-column:1/-1}.inicio-nuevo-grid label{display:flex;flex-direction:column;gap:5px;font-size:10px;font-weight:700;color:#285a7d;text-transform:uppercase}.inicio-nuevo-grid input,.inicio-nuevo-grid select,.inicio-nuevo-grid textarea{width:100%;box-sizing:border-box;border:1px solid #c9dce8;border-radius:7px;padding:8px 9px;background:#fff;color:#214e6d;font:inherit;font-size:11px;outline:none;text-transform:uppercase}.inicio-nuevo-grid textarea{min-height:72px;resize:vertical}.inicio-nuevo-grid input:focus,.inicio-nuevo-grid select:focus,.inicio-nuevo-grid textarea:focus{border-color:#249bd5;box-shadow:0 0 0 2px #249bd51a}.inicio-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.inicio-modal-actions button{height:32px;border-radius:7px;padding:5px 12px;border:1px solid #c9dce8;font-size:10px;font-weight:800;cursor:pointer}.inicio-modal-actions .primary{background:#126fae;color:#fff;border-color:#126fae}.inicio-modal-actions .secondary{background:#fff;color:#285a7d}@media(max-width:760px){.inicio-card>.toolbar.inicio-toolbar{left:10px!important;right:10px!important;gap:6px!important;overflow-x:auto!important;padding-bottom:3px}.inicio-nuevo-grid{grid-template-columns:1fr}.inicio-nuevo-grid .full{grid-column:auto}}
    `;document.head.appendChild(style);}
  function rows(){return Array.isArray(cache.inicio)?cache.inicio:[];}
  function statusClass(value){const v=norm(value);if(v==="PENDIENTE"||v==="PENDIENTE POR GESTION")return "gestion-status-pendiente";if(v==="PROCESO"||v==="EN PROCESO")return "gestion-status-proceso";if(v==="TERMINADO")return "gestion-status-terminado";if(v==="DEVUELTO")return "gestion-status-devuelto";return "";}
  function rowClass(value){const v=norm(value);if(v==="PENDIENTE"||v==="PENDIENTE POR GESTION")return "gestion-row-pendiente";if(v==="PROCESO"||v==="EN PROCESO")return "gestion-row-proceso";if(v==="TERMINADO")return "gestion-row-terminado";if(v==="DEVUELTO")return "gestion-row-devuelto";return "";}
  function applyInicioStatusColors(root){const scope=root||document;scope.querySelectorAll(".inicio-table tbody tr").forEach(tr=>{tr.classList.remove("gestion-row-pendiente","gestion-row-proceso","gestion-row-terminado","gestion-row-devuelto");const el=tr.querySelector(".inicio-status-edit");if(!el)return;el.classList.remove("gestion-status-pendiente","gestion-status-proceso","gestion-status-terminado","gestion-status-devuelto");const sc=statusClass(el.value);if(sc)el.classList.add(sc);const rc=rowClass(el.value);if(rc)tr.classList.add(rc);});}
  function syncStatusSelectColor(el){if(!el)return;el.classList.remove("gestion-status-pendiente","gestion-status-proceso","gestion-status-terminado","gestion-status-devuelto");const sc=statusClass(el.value);if(sc)el.classList.add(sc);}
  function bindStatusColorChange(){if(document.documentElement.dataset.inicioStatusSelectColorBound==="1")return;document.documentElement.dataset.inicioStatusSelectColorBound="1";document.addEventListener("change",function(e){const el=e.target;if(!el?.matches(".inicio-table .inicio-status-edit"))return;syncStatusSelectColor(el);const tr=el.closest("tr");if(tr){tr.classList.remove("gestion-row-pendiente","gestion-row-proceso","gestion-row-terminado","gestion-row-devuelto");const rc=rowClass(el.value);if(rc)tr.classList.add(rc);}},true);}
  function toolbarHtml(){return '<div class="toolbar inicio-toolbar" data-inicio-toolbar-version="'+TOOLBAR_VERSION+'"><button type="button" onclick="inicioNuevo()">+ NUEVO</button><button type="button" class="alt" onclick="importInicioXlsx()">IMPORTAR XLSX</button><button type="button" class="alt" onclick="exportInicioXlsx()">EXPORTAR XLSX</button><button type="button" class="alt clear-filters-btn" onclick="clearInicioFilters()">LIMPIAR FILTROS</button><span class="muted">'+rows().length+' REGISTROS</span></div>';}
  function patch(){const content=$("content"),title=$("title");if(!content||!title||norm(title.textContent)!=="INICIO")return;const card=content.querySelector(".inicio-card"),table=card?.querySelector(".inicio-table");if(!card||!table)return;ensureStyle();let tb=card.querySelector(".inicio-toolbar");if(!tb){const old=card.querySelector(":scope>.toolbar");if(old)old.outerHTML=toolbarHtml();else card.insertAdjacentHTML("afterbegin",toolbarHtml());tb=card.querySelector(".inicio-toolbar");}if(tb){tb.dataset.inicioToolbarVersion=TOOLBAR_VERSION;const c=tb.querySelector(".muted"),txt=rows().length+" REGISTROS";if(c&&c.textContent!==txt)c.textContent=txt;}const wrap=card.querySelector(".tablewrap");if(wrap){wrap.classList.add("inicio-scroll-wrap");wrap.style.marginTop="60px";wrap.style.overflowX="auto";wrap.style.overflowY="auto";wrap.style.height="calc(450px - 78px)";wrap.style.maxHeight="none";table.style.minWidth="1245px";table.style.width="max-content";}applyInicioStatusColors(card);window.__INICIO_TOOLBAR_READY__=true;}
  function modal(){let m=document.getElementById("inicio-nuevo-modal");if(m)return m;m=document.createElement("div");m.id="inicio-nuevo-modal";m.className="modal hidden";m.innerHTML='<div class="modalbox"><button type="button" class="x" data-close-inicio>×</button><h3>NUEVO REGISTRO — INICIO</h3><form id="inicio-nuevo-form"><div class="inicio-nuevo-grid"><label>NIT<input name="nit" required></label><label>EXPEDIENTE<input name="expediente" required></label><label>RAZÓN SOCIAL<input name="razon_social" required></label><label>FECHA PRESCRIPCIÓN<input name="fecha_prescripcion" inputmode="numeric" maxlength="10" placeholder="DD/MM/AA"></label><label>ESTADO<select name="estado">'+ESTADOS.map(s=>'<option value="'+s+'">'+s+'</option>').join('')+'</select></label><label class="full">OBSERVACIONES<textarea name="observaciones"></textarea></label></div><div class="inicio-modal-actions"><button type="button" class="secondary" data-close-inicio>CANCELAR</button><button type="submit" class="primary">GUARDAR</button></div></form></div>';document.body.appendChild(m);m.querySelectorAll("[data-close-inicio]").forEach(b=>b.addEventListener("click",()=>m.classList.add("hidden")));m.addEventListener("click",e=>{if(e.target===m)m.classList.add("hidden")});m.querySelector("[name=estado]").value="PENDIENTE";m.querySelector("[name=fecha_prescripcion]")?.addEventListener("input",e=>e.target.value=formatDateTyping(e.target.value));m.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),payload={nit:norm(d.get("nit")),expediente:norm(d.get("expediente")),razon_social:norm(d.get("razon_social")),fecha_prescripcion:toIso(d.get("fecha_prescripcion"))||null,estado:norm(d.get("estado"))||"PENDIENTE",observaciones:norm(d.get("observaciones"))||null};if(!payload.nit||!payload.expediente||!payload.razon_social){alert("NIT, EXPEDIENTE Y RAZÓN SOCIAL SON OBLIGATORIOS.");return;}const b=f.querySelector("button[type=submit]");b.disabled=true;try{const r=await db.from("cartera_inicio").insert(payload).select("id,nit,expediente,razon_social,fecha_prescripcion,estado,observaciones").single();if(r.error)throw r.error;m.classList.add("hidden");f.reset();m.querySelector("[name=estado]").value="PENDIENTE";if(typeof window.refreshInicio==="function")await window.refreshInicio();}catch(err){console.error("ERROR NUEVO INICIO",err);alert("NO FUE POSIBLE CREAR EL REGISTRO: "+(err.message||err));}finally{b.disabled=false;}});return m;}
  window.inicioNuevo=function(){ensureStyle();const m=modal();m.classList.remove("hidden");m.querySelector("[name=nit]")?.focus();};
  window.exportInicioXlsx=function(){try{if(!window.XLSX)throw Error("NO SE ENCUENTRA EL MÓDULO XLSX.");const data=rows().map(r=>({NIT:r.nit||"",EXPEDIENTE:r.expediente||"",["RAZÓN SOCIAL"]:r.razon_social||"",["FECHA PRESCRIPCIÓN"]:r.fecha_prescripcion||"",ESTADO:r.estado||"",OBSERVACIONES:r.observaciones||""}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Inicio");XLSX.writeFile(wb,"Inventario_Cartera_Inicio.xlsx");}catch(e){alert("NO FUE POSIBLE EXPORTAR INICIO: "+(e.message||e));}};
  window.importInicioXlsx=function(){if(!window.XLSX){alert("NO SE ENCUENTRA EL MÓDULO XLSX.");return;}const input=document.createElement("input");input.type="file";input.accept=".xlsx,.xls";input.style.display="none";document.body.appendChild(input);input.addEventListener("change",async()=>{const file=input.files?.[0];if(!file){input.remove();return;}try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:""});if(!raw.length)throw Error("EL ARCHIVO NO CONTIENE REGISTROS.");const key=h=>norm(h).normalize("NFD").replace(/[\u0300-\u036f]/g,"");const find=(r,n)=>{const k=Object.keys(r).find(x=>n.includes(key(x)));return k?r[k]:""};const payload=raw.map(r=>({nit:norm(find(r,["NIT","IDENTIFICACION","IDENTIFICACION CONTRIBUYENTE"])),expediente:norm(find(r,["EXPEDIENTE","NUMERO EXPEDIENTE","N EXPEDIENTE"])),razon_social:norm(find(r,["RAZON SOCIAL","RAZON SOCIAL CONTRIBUYENTE","CONTRIBUYENTE"])),fecha_prescripcion:toIso(find(r,["FECHA PRESCRIPCION","FECHA DE PRESCRIPCION","FECHA PRESCRIPCIÓN"])),estado:norm(find(r,["ESTADO","GESTION","GESTIÓN"]))||"PENDIENTE",observaciones:norm(find(r,["OBSERVACIONES","OBSERVACION","COMENTARIOS","COMENTARIO"]))||null})).filter(r=>r.nit||r.expediente||r.razon_social);if(!payload.length)throw Error("NO SE ENCONTRARON COLUMNAS DE INICIO RECONOCIBLES.");const r=await db.from("cartera_inicio").insert(payload);if(r.error)throw r.error;await window.refreshInicio();alert("IMPORTACIÓN COMPLETADA: "+payload.length+" REGISTROS.");}catch(e){console.error("ERROR IMPORTANDO INICIO",e);alert("NO FUE POSIBLE IMPORTAR EL ARCHIVO: "+(e.message||e));}finally{input.remove();}},{once:true});input.click();};
  function start(){ensureStyle();bindStatusColorChange();const content=$("content");if(!content)return;const observer=new MutationObserver(()=>patch());observer.observe(content,{childList:true,subtree:true});patch();setTimeout(patch,150);setTimeout(patch,700);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
})();
